/**
 * LLM Guard — Moteur de détection avancé
 *
 * 4 couches de détection, du plus rapide au plus intelligent :
 *
 *   Couche 1 : Regex (< 1ms)        → forme exacte des PII
 *   Couche 2 : Fuzzy matching (< 5ms) → fautes, obfuscation, variantes
 *   Couche 3 : Règles contextuelles (< 10ms) → combinaisons suspectes
 *   Couche 4 : Classification LLM (~ 1-2s)   → compréhension sémantique
 *
 * Les couches 1-3 tournent côté client (navigateur).
 * La couche 4 appelle un LLM classifieur (optionnelle, nécessite une API key).
 *
 * Note: This file is a Node.js module used only by tests — it is NOT loaded
 * by the Chrome extension at runtime.
 */

// Shared modules (Node.js imports)
const { PII_PATTERNS } = require("./rules/pii-patterns.js");
const { SENSITIVE_KEYWORDS_CATEGORIZED } = require("./rules/sensitive-keywords-categorized.js");
const { CONTEXT_RULES } = require("./rules/context-rules.js");
const { levenshtein, normalize, getMaxSeverity, deduplicateFindings } = require("./utils.js");

// Company-specific rules (optional, generated by build.js)
let COMPANY_BLACKLIST = [];
let COMPANY_BLACKLIST_REGEX = [];
try {
  const companyRules = require("./config/company-rules.js");
  COMPANY_BLACKLIST = companyRules.COMPANY_BLACKLIST || [];
  COMPANY_BLACKLIST_REGEX = companyRules.COMPANY_BLACKLIST_REGEX || [];
} catch { /* no company config — that's fine */ }

// Re-export as SENSITIVE_KEYWORDS for backward compatibility with existing API
const SENSITIVE_KEYWORDS = [...SENSITIVE_KEYWORDS_CATEGORIZED, ...COMPANY_BLACKLIST];

// ═══════════════════════════════════════════════════════════════
// COUCHE 1 — REGEX (identique à v2, la base)
// ═══════════════════════════════════════════════════════════════

function scanRegex(text) {
  const findings = [];
  for (const p of PII_PATTERNS) {
    const regex = new RegExp(p.regex.source, p.regex.flags);
    const raw = text.match(regex);
    if (!raw) continue;
    const filtered = typeof p.validate === "function"
      ? raw.filter((m) => p.validate(m))
      : raw;
    if (filtered.length === 0) continue;
    findings.push({
      layer: "regex",
      type: p.name,
      severity: p.severity,
      count: filtered.length,
      matches: [...new Set(filtered)],
    });
  }
  return findings;
}


// ═══════════════════════════════════════════════════════════════
// COUCHE 2 — FUZZY MATCHING
// Attrape les fautes de frappe, l'obfuscation, les variantes
// ═══════════════════════════════════════════════════════════════

function scanFuzzy(text) {
  const findings = [];
  const normalizedText = normalize(text);
  const words = text.toLowerCase().split(/\s+/);

  for (const kw of SENSITIVE_KEYWORDS) {
    const normalizedKw = normalize(kw.term);

    // --- Recherche exacte (insensible casse + accents) ---
    if (normalizedText.includes(normalizedKw)) {
      findings.push({
        layer: "fuzzy",
        type: `Mot-clé: ${kw.term}`,
        severity: "medium",
        category: kw.category,
        matchType: "exact",
        matches: [kw.term],
      });
      continue;
    }

    // --- Recherche par Levenshtein sur les mots individuels ---
    // Seulement pour les termes d'un seul mot (≥ 5 caractères)
    if (!kw.term.includes(" ") && kw.term.length >= 5) {
      const threshold = kw.term.length <= 6 ? 1 : 2; // tolérance proportionnelle

      for (const word of words) {
        const normalizedWord = normalize(word);
        if (normalizedWord.length < normalizedKw.length - 2) continue;
        if (normalizedWord.length > normalizedKw.length + 2) continue;

        const distance = levenshtein(normalizedWord, normalizedKw, threshold);
        if (distance > 0 && distance <= threshold) {
          findings.push({
            layer: "fuzzy",
            type: `Mot-clé (approx): ${kw.term}`,
            severity: "low",
            category: kw.category,
            matchType: "levenshtein",
            distance,
            original: word,
            matches: [word],
          });
          break;
        }
      }
    }

    // --- Recherche de groupes de mots éclatés ---
    // "bulletin de paie" → cherche si tous les mots sont présents proches
    if (kw.term.includes(" ")) {
      const kwWords = kw.term.toLowerCase().split(/\s+/);
      const allPresent = kwWords.every((w) =>
        words.some((tw) => {
          const nw = normalize(tw);
          const nkw = normalize(w);
          return nw === nkw || (nkw.length >= 4 && levenshtein(nw, nkw, 1) <= 1);
        })
      );
      if (allPresent && !normalizedText.includes(normalizedKw)) {
        // Vérifier la proximité (mots dans une fenêtre de 8 mots)
        const positions = kwWords.map((w) => {
          const nw = normalize(w);
          return words.findIndex((tw) => {
            const ntw = normalize(tw);
            return ntw === nw || (nw.length >= 4 && levenshtein(ntw, nw, 1) <= 1);
          });
        });
        const minPos = Math.min(...positions);
        const maxPos = Math.max(...positions);
        if (maxPos - minPos <= 8) {
          findings.push({
            layer: "fuzzy",
            type: `Groupe de mots (dispersé): ${kw.term}`,
            severity: "low",
            category: kw.category,
            matchType: "dispersed",
            matches: [words.slice(minPos, maxPos + 1).join(" ")],
          });
        }
      }
    }
  }

  return findings;
}

// --- 2d. Détection d'obfuscation intentionnelle ---
// Quelqu'un qui écrit "s.a.l.a.i.r.e" ou "s4l41r3" essaie
// probablement de contourner le filtre → sévérité augmentée.

function detectObfuscation(text) {
  const findings = [];

  // Pattern : lettres séparées par des points/tirets/espaces
  // "c.o.n.f.i.d.e.n.t.i.e.l" ou "s a l a i r e"
  const spaced = text.match(
    /\b([a-zA-ZÀ-ÿ][\s.\-_*]{1,2}){4,}[a-zA-ZÀ-ÿ]\b/g
  );
  if (spaced) {
    for (const match of spaced) {
      const collapsed = normalize(match);
      for (const kw of SENSITIVE_KEYWORDS) {
        const nkw = normalize(kw.term);
        if (collapsed === nkw || levenshtein(collapsed, nkw, 1) <= 1) {
          findings.push({
            layer: "fuzzy",
            type: `Obfuscation détectée: ${kw.term}`,
            severity: "high",
            category: kw.category,
            matchType: "obfuscation",
            original: match,
            matches: [match],
          });
        }
      }
    }
  }

  // Pattern : mélange chiffres/lettres suspect (leetspeak)
  const leet = text.match(/\b[a-zA-Z]*[\d@$!]+[a-zA-Z]+[\d@$!]*[a-zA-Z]*\b/g);
  if (leet) {
    for (const match of leet) {
      if (match.length < 5) continue;
      const collapsed = normalize(match);
      for (const kw of SENSITIVE_KEYWORDS) {
        const nkw = normalize(kw.term);
        if (collapsed === nkw || levenshtein(collapsed, nkw, 1) <= 1) {
          findings.push({
            layer: "fuzzy",
            type: `Leetspeak détecté: ${kw.term}`,
            severity: "high",
            category: kw.category,
            matchType: "leetspeak",
            original: match,
            matches: [match],
          });
        }
      }
    }
  }

  // Pattern : email écrit en toutes lettres
  const spelledEmail =
    /(\w+)\s+(?:point|dot)\s+(\w+)\s+(?:arobase|arrobase|at|chez)\s+(\w+)\s+(?:point|dot)\s+(\w+)/gi;
  const emailMatch = spelledEmail.exec(text);
  if (emailMatch) {
    const reconstructed = `${emailMatch[1]}.${emailMatch[2]}@${emailMatch[3]}.${emailMatch[4]}`;
    findings.push({
      layer: "fuzzy",
      type: "Email obfusqué (épelé)",
      severity: "high",
      matchType: "spelled-email",
      original: emailMatch[0],
      reconstructed,
      matches: [emailMatch[0]],
    });
  }

  // Pattern : numéro de téléphone en toutes lettres
  const phoneWords =
    /(?:z[ée]ro|zero)\s+(?:six|sept|un|deux|trois|quatre|cinq|huit|neuf)\b.*?(?:(?:z[ée]ro|zero|un|deux|trois|quatre|cinq|six|sept|huit|neuf|dix|onze|douze|treize|quatorze|quinze|seize|vingt|trente|quarante|cinquante|soixante)[\s,\-]*){4,}/gi;
  const phoneMatch = phoneWords.exec(text);
  if (phoneMatch) {
    findings.push({
      layer: "fuzzy",
      type: "Téléphone obfusqué (en lettres)",
      severity: "high",
      matchType: "spelled-phone",
      original: phoneMatch[0],
      matches: [phoneMatch[0]],
    });
  }

  return findings;
}


// ═══════════════════════════════════════════════════════════════
// COUCHE 3 — RÈGLES CONTEXTUELLES
// Analyse les combinaisons de mots qui, ensemble, révèlent
// une information sensible — même si aucun mot isolé n'est suspect.
// ═══════════════════════════════════════════════════════════════

function scanContextual(text) {
  const findings = [];

  for (const rule of CONTEXT_RULES) {
    // Chaque règle a 2 indicateurs qui doivent être présents ensemble
    const indicators = Object.entries(rule).filter(
      ([k, v]) => k.endsWith("Indicators") && v instanceof RegExp
    );

    const allMatch = indicators.every(([, regex]) => regex.test(text));

    if (allMatch) {
      // Extraire les portions matchées pour le rapport
      const evidence = indicators.map(([key, regex]) => {
        const match = text.match(regex);
        return { indicator: key.replace("Indicators", ""), match: match?.[0] };
      });

      findings.push({
        layer: "contextual",
        type: rule.name,
        severity: rule.severity,
        category: rule.category,
        description: rule.description,
        evidence,
        matches: evidence.map((e) => e.match).filter(Boolean),
      });
    }
  }

  return findings;
}


// ═══════════════════════════════════════════════════════════════
// COUCHE 4 — CLASSIFICATION PAR LLM
// Le plus puissant : un LLM analyse le prompt pour comprendre
// le SENS, pas juste la forme.
//
// Architecture : le prompt est envoyé à Claude (via API Anthropic)
// AVANT d'être envoyé à ChatGPT/Gemini/etc.
// ═══════════════════════════════════════════════════════════════

// API credentials are read from the environment, never from this file.
// Hardcoding `apiKey` here risks a commit leaking a live Anthropic credential
// to git history; pulling from `process.env` keeps the secret out of the repo
// and makes CI/local-dev enablement explicit (`LLM_GUARD_CLASSIFIER_KEY=...`).
const LLM_CLASSIFIER_CONFIG = {
  enabled: process.env.LLM_GUARD_CLASSIFIER_ENABLED === "1",
  apiUrl: "https://api.anthropic.com/v1/messages",
  get apiKey() { return process.env.LLM_GUARD_CLASSIFIER_KEY || ""; },
  model: "claude-sonnet-4-20250514",
  maxTokens: 300,
  confidenceThreshold: 0.7,
  timeout: 3000,
};

const CLASSIFIER_SYSTEM_PROMPT = `Tu es un classificateur de données personnelles pour la conformité RGPD.

Analyse le texte fourni et réponds UNIQUEMENT avec un JSON valide (sans backticks) :

{
  "contains_pii": true/false,
  "confidence": 0.0-1.0,
  "findings": [
    {
      "type": "catégorie RGPD",
      "severity": "critical|high|medium|low",
      "description": "explication courte",
      "evidence": "extrait du texte"
    }
  ],
  "reasoning": "explication en une phrase"
}

Catégories à détecter :
- Données d'identification (nom, prénom, surnom, photo)
- Coordonnées (adresse, téléphone, email)
- Données financières (salaire, revenus, comptes bancaires)
- Données médicales (santé, handicap, traitements)
- Données sensibles art. 9 RGPD (religion, opinions politiques, orientation sexuelle, appartenance syndicale, données biométriques/génétiques)
- Données judiciaires (casier, infractions, condamnations)
- Données professionnelles confidentielles (évaluations, sanctions, licenciements)
- Identification indirecte (combinaison de données qui permettrait d'identifier une personne)
- Données de mineurs

IMPORTANT : ne flag PAS les questions génériques sur ces sujets.
"Quel est le salaire moyen en France ?" = pas de PII.
"Le salaire de Jean Dupont est de 45000€" = PII.

La distinction clé : est-ce qu'une personne RÉELLE et IDENTIFIABLE est concernée ?`;

async function classifyWithLLM(text) {
  if (!LLM_CLASSIFIER_CONFIG.enabled || !LLM_CLASSIFIER_CONFIG.apiKey) {
    return [];
  }

  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(
      () => controller.abort(),
      LLM_CLASSIFIER_CONFIG.timeout
    );

    // IMPORTANT : on utilise la vraie fetch, pas celle qu'on a monkey-patché
    const response = await window.__originalFetch(
      LLM_CLASSIFIER_CONFIG.apiUrl,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": LLM_CLASSIFIER_CONFIG.apiKey,
          "anthropic-version": "2023-06-01",
          "anthropic-dangerous-direct-browser-access": "true",
        },
        body: JSON.stringify({
          model: LLM_CLASSIFIER_CONFIG.model,
          max_tokens: LLM_CLASSIFIER_CONFIG.maxTokens,
          system: CLASSIFIER_SYSTEM_PROMPT,
          messages: [
            {
              role: "user",
              content: `Analyse ce texte pour la conformité RGPD :\n\n${text}`,
            },
          ],
        }),
        signal: controller.signal,
      }
    );

    clearTimeout(timeoutId);

    if (!response.ok) {
      console.warn("[LLM Guard] Classificateur LLM erreur:", response.status);
      return [];
    }

    const data = await response.json();
    const resultText = data.content?.[0]?.text || "";

    // Parser le JSON de la réponse
    const result = JSON.parse(resultText.replace(/```json?|```/g, "").trim());

    if (
      !result.contains_pii ||
      result.confidence < LLM_CLASSIFIER_CONFIG.confidenceThreshold
    ) {
      return [];
    }

    return (result.findings || []).map((f) => ({
      layer: "llm",
      type: f.type,
      severity: f.severity || "medium",
      description: f.description,
      evidence: f.evidence,
      confidence: result.confidence,
      reasoning: result.reasoning,
      matches: [f.evidence].filter(Boolean),
    }));
  } catch (err) {
    if (err.name === "AbortError") {
      console.warn("[LLM Guard] Classificateur LLM timeout");
    } else {
      console.warn("[LLM Guard] Classificateur LLM erreur:", err.message);
    }
    return [];
  }
}


// ═══════════════════════════════════════════════════════════════
// ORCHESTRATEUR — Combine les 4 couches
// ═══════════════════════════════════════════════════════════════

// ─── Company blacklist regex patterns ─────────────────────────
function scanCompanyBlacklistRegex(text) {
  const findings = [];
  for (const entry of COMPANY_BLACKLIST_REGEX) {
    try {
      const regex = new RegExp(entry.pattern, "gi");
      const matches = text.match(regex);
      if (matches && matches.length > 0) {
        findings.push({
          layer: "company-blacklist",
          type: `Blacklist: ${entry.category}`,
          severity: entry.severity || "high",
          category: entry.category,
          matchType: "regex",
          matches: matches.slice(0, 3),
        });
      }
    } catch { /* skip invalid regex */ }
  }
  return findings;
}

async function analyzePrompt(text) {
  const startTime = performance.now();

  // Couches 1-3 en parallèle (synchrones, très rapides)
  const regexFindings = scanRegex(text);
  const fuzzyFindings = scanFuzzy(text);
  const obfuscationFindings = detectObfuscation(text);
  const contextFindings = scanContextual(text);
  const companyRegexFindings = scanCompanyBlacklistRegex(text);

  // Couche 4 : uniquement si les couches précédentes n'ont rien trouvé
  // OU si on veut une double vérification
  let llmFindings = [];
  const localFindings = [
    ...regexFindings,
    ...fuzzyFindings,
    ...obfuscationFindings,
    ...contextFindings,
    ...companyRegexFindings,
  ];

  if (LLM_CLASSIFIER_CONFIG.enabled) {
    // Si rien trouvé localement, ou si le texte est long/complexe
    if (localFindings.length === 0 || text.length > 200) {
      llmFindings = await classifyWithLLM(text);
    }
  }

  const allFindings = [...localFindings, ...llmFindings];

  // Dédupliquer les findings similaires
  const deduped = deduplicateFindings(allFindings);

  const elapsed = performance.now() - startTime;

  return {
    findings: deduped,
    stats: {
      totalFindings: deduped.length,
      byLayer: {
        regex: regexFindings.length,
        fuzzy: fuzzyFindings.length + obfuscationFindings.length,
        contextual: contextFindings.length,
        llm: llmFindings.length,
      },
      elapsed: Math.round(elapsed),
      hasCritical: deduped.some((f) => f.severity === "critical"),
      maxSeverity: getMaxSeverity(deduped),
    },
  };
}


// ═══════════════════════════════════════════════════════════════
// EXPORTS (pour les tests)
// ═══════════════════════════════════════════════════════════════

if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    // Re-exported from shared modules
    PII_PATTERNS,
    levenshtein,
    normalize,
    CONTEXT_RULES,
    // Business logic
    scanRegex,
    scanFuzzy,
    detectObfuscation,
    scanContextual,
    scanCompanyBlacklistRegex,
    analyzePrompt,
    SENSITIVE_KEYWORDS,
    COMPANY_BLACKLIST,
    COMPANY_BLACKLIST_REGEX,
  };
}
